// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0Zdc-3aYw9SyPyf5LbOjtZw7FMRQKwk',
    appId: '1:747750029310:web:0db0be289427653fd132af',
    messagingSenderId: '747750029310',
    projectId: 'drenchmate-6f39c',
    authDomain: 'drenchmate-6f39c.firebaseapp.com',
    storageBucket: 'drenchmate-6f39c.appspot.com',
    measurementId: 'G-Y9X7LL0XDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVGFMawYK7wKIi8KXW0letwzSpxnMmFM',
    appId: '1:747750029310:android:3c636d51446ca65dd132af',
    messagingSenderId: '747750029310',
    projectId: 'drenchmate-6f39c',
    storageBucket: 'drenchmate-6f39c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYy-hBUBV-R7MFCA_W0cNG8bwdgO5JA0A',
    appId: '1:747750029310:ios:9daa12f1211f2a36d132af',
    messagingSenderId: '747750029310',
    projectId: 'drenchmate-6f39c',
    storageBucket: 'drenchmate-6f39c.appspot.com',
    iosBundleId: 'com.example.drenchmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYy-hBUBV-R7MFCA_W0cNG8bwdgO5JA0A',
    appId: '1:747750029310:ios:9daa12f1211f2a36d132af',
    messagingSenderId: '747750029310',
    projectId: 'drenchmate-6f39c',
    storageBucket: 'drenchmate-6f39c.appspot.com',
    iosBundleId: 'com.example.drenchmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0Zdc-3aYw9SyPyf5LbOjtZw7FMRQKwk',
    appId: '1:747750029310:web:ecf03592514587efd132af',
    messagingSenderId: '747750029310',
    projectId: 'drenchmate-6f39c',
    authDomain: 'drenchmate-6f39c.firebaseapp.com',
    storageBucket: 'drenchmate-6f39c.appspot.com',
    measurementId: 'G-R0FCPMPRJ8',
  );

}